name: ECR Push Image with Commit Message

on:
  push:
    branches:
      - 'main'
#    tags:
#      - v*  # 'v' で始まるタグに反応（例: v1.0.0）

jobs:
  extract-commit-message:
    runs-on: ubuntu-latest
    outputs:
      repository-name: ${{ steps.extract-repo-name.outputs.repository-name }}
    steps:
      - uses: actions/checkout@v3
      - id: extract-repo-name
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_message"
          repository_name=$(echo "$commit_message" | grep -oP '(?<=<).*(?=>)')
          echo "::set-output name=repository-name::${repository_name}"

  push:
    runs-on: ubuntu-latest
    needs: extract-commit-message
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment variables
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "AWS_ROLE_TO_ASSUME=${{ secrets.AWS_ROLE_TO_ASSUME }}" >> $GITHUB_ENV
          echo "REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" >> $GITHUB_ENV
          REPOSITORY_NAME=${{ needs.extract-commit-message.outputs.repository-name }}
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${REPOSITORY_NAME}:${IMAGE_TAG}"
          echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV

      # 環境変数を出力するステップ
      - name: Print Environment Variables
        run: |
          echo "AWS Region: $AWS_REGION"
          echo "AWS Role to Assume: $AWS_ROLE_TO_ASSUME"
          echo "Registry: $REGISTRY"
          echo "Repository Name: $REPOSITORY_NAME"
          echo "Image Tag: $IMAGE_TAG"
          echo "Image URI: $IMAGE_URI"

      # AWS 認証
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions

      # ECR ログイン
      - uses: aws-actions/amazon-ecr-login@v1

      # Docker イメージを build・push する
      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_URI }}${{ env.IMAGE_TAG }} ./${{ env.REPOSITORY_NAME }} -f ${{ env.REPOSITORY_NAME }}/docker/Dockerfile
          docker images
          docker push ${{ env.IMAGE_URI }}${{ env.IMAGE_TAG }}

#  deploy:
#    runs-on: ubuntu-latest
#    needs: push
#    steps:
#      - uses: actions/checkout@v3
#
#      # AWS 認証
#      - uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-region: ${{ env.AWS_REGION }}
#          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
#          role-session-name: GitHubActions

      - name: Deploy to CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/cloudformation-template.yml \
            --stack-name your-stack-name \
            --parameter-overrides ImageUri=${{ env.IMAGE_URI }} FunctionName=${{ env.REPOSITORY_NAME }} \
            --capabilities CAPABILITY_IAM
